version: '3.8'

services:
  bitcoin-core:
    image: bitcoin/bitcoin:28-alpine
    container_name: bitcoin-core
    profiles: [regtest]
    command:
      - -conf=/etc/bitcoin/bitcoin.conf
    ports:
      - "${BITCOIN_RPC_PORT}:18443"
      - "18444:18444"
    volumes:
      - bitcoin-data:/home/bitcoin/.bitcoin
      - ./data:/data
    configs:
      - source: bitcoin_conf
        target: /etc/bitcoin/bitcoin.conf
    environment:
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
    networks:
      - bitcoin-net
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-regtest", "-rpcuser=${BITCOIN_RPC_USER}", "-rpcpassword=${BITCOIN_RPC_PASSWORD}", "getblockchaininfo"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

configs:
  bitcoin_conf:
    content: |
      # Global Settings
      regtest=1
      server=1
      printtoconsole=1
      
      # RPC Authentication (applies to all networks)
      rpcuser=${BITCOIN_RPC_USER}
      rpcpassword=${BITCOIN_RPC_PASSWORD}
      
      # Regtest-specific Settings
      [regtest]
      rpcallowip=0.0.0.0/0
      rpcbind=0.0.0.0
      fallbackfee=0.00001
      txindex=1
      dbcache=512

volumes:
  bitcoin-data:

networks:
  bitcoin-net:
    driver: bridge
